#!/usr/bin/env bash
# detect-secrets over this repo.
#
#   ./scripts/scan-repo.sh          # check (exit 1 on a new finding)
#   ./scripts/scan-repo.sh --update # rewrite .secrets.baseline
#
# The exclusion list is baked INTO the baseline with --exclude-files, not passed
# as a flag here. That matters: a plain `detect-secrets-hook --baseline
# .secrets.baseline` reads the filters recorded in the baseline and applies them,
# so this script and the standard command cannot disagree about what is excluded.
# Keeping the regex only in this script made the standard command fail on files
# that had been deliberately excluded.
#
# What is excluded and why:
#   pnpm-lock.yaml  autogenerated by pnpm; a wall of sha512 integrity hashes
#   dist/           the committed bundle, i.e. all of node_modules concatenated
set -euo pipefail
cd "$(dirname "$0")/.."

EXCLUDE='(^|/)(pnpm-lock\.yaml|\.secrets\.baseline)$|(^|/)dist/'

# `find`, not `git ls-files`: the file list must not depend on git index state.
# A mid-staging index silently yields a short list, and a scan over three files
# reports "clean" exactly like a scan over all of them.
# The `./` prefix is stripped on purpose. `detect-secrets scan` normalises it away
# when it writes the baseline, but `detect-secrets-hook` does NOT normalise the
# paths it is given — so `./tests/x.ts` fails to match the baseline's
# `tests/x.ts` and every audited finding comes back as new.
files0() {
  find . \
    \( -path ./node_modules -o -path ./.git -o -path ./output -o -path ./coverage \) \
    -prune -o -type f -print0 \
  | python3 -c 'import sys
buf = sys.stdin.buffer.read()
paths = [p for p in buf.split(b"\0") if p]
out = [p[2:] if p.startswith(b"./") else p for p in paths]
sys.stdout.buffer.write(b"\0".join(out) + (b"\0" if out else b""))'
}

if ! command -v detect-secrets >/dev/null 2>&1; then
  echo "detect-secrets is not installed. Install it with:" >&2
  echo "  brew install detect-secrets   # or: pip install detect-secrets" >&2
  exit 127
fi

count=$(files0 | tr -dc '\0' | wc -c | tr -d ' ')
if [ "$count" -lt 20 ]; then
  echo "refusing to scan: only $count files found, which cannot be right" >&2
  exit 1
fi

if [ "${1:-}" = "--update" ]; then
  files0 | xargs -0 detect-secrets scan --exclude-files "$EXCLUDE" > .secrets.baseline
  echo "Wrote .secrets.baseline over $count files. Review it, then audit anything real:"
  echo "  detect-secrets audit .secrets.baseline"
  exit 0
fi

echo "scanning $count files"
files0 | xargs -0 detect-secrets-hook --baseline .secrets.baseline
